### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by p-moreira** [sindresorhus/ky-universal#14]
Hi, I'm using ky-universal in a nuxtjs project and at the build there is an error:

```WARNING in ./node_modules/ky-universal/index.js
Module not found: Error: Can't resolve 'web-streams-polyfill/ponyfill/es2018'```

What can I do to solve this Issue?

Thanks

**Comment by sindresorhus** [comment]
This is an issue with NuxtJS’s build system. That dependency is marked optional. Open an issue on NuxtJS instead.
