### ISSUE TITLE
Prefer own version of node-fetch or allow users to specify it

### ISSUE THREAD

**Issue by paambaati** [sindresorhus/ky-universal#20]
I just reported an issue on the Next.js issue tracker that concerns `ky-universal` — https://github.com/vercel/next.js/issues/13549

tl;dr

The body timeout issue on parsing large JSON responses still happens with `v0.7.0` when using Next.js.

A contributor pointed out (see https://github.com/vercel/next.js/issues/13549#issuecomment-636066828) that this is happening because `ky-universal` is preferring global `fetch` over the latest beta version (own dependency). How do you propose we solve this?

One option I can think of is letting users inject their version of `node-fetch`. Another way to solve this would be expose a flag to force-use the bundled version of `node-fetch`.

Are there better solutions?

**Comment by belgattitude** [comment]
Affected as well...

I like the idea to use *recommended* version... By recommended I mean the version ky-universal use for its tests (the latest is node-fetch v3.beta.x). 

Not sure if it's possible to drive this by params... maybe a separate export `import ky from 'ky-universal-full`...

**Comment by sindresorhus** [comment]
This package is no longer needed if you target Node.js 18 or later: https://github.com/sindresorhus/ky/releases/tag/v1.0.0
