### ISSUE TITLE
Es-bundle getting imported on Vercel

### ISSUE THREAD

**Issue by privatenumber** [sindresorhus/ky-universal#23]
This was happening via [nuxt/http](https://github.com/nuxt/http) which uses ky and a copied implementation of ky-universal.

I figured this should also be fixed here too.

https://github.com/nuxt/http/pull/121

**Comment by sindresorhus** [comment]
I don't have all the context. What's to fix here? It sounds like a bug in the "Vercel bundle importer". `ky-universal` is working fine everywhere else.

**Comment by sholladay** [comment]
This seems like some kind of proprietary environment issue. I see nothing that justifies why this logic belongs in Ky specifically. If anything, it sounds like it affects all `node-fetch` users and should be fixed there. But ultimately, it's probably a wider issue with the module loader.

**Comment by privatenumber** [comment]
Those are fair points.
We landed a fix in nuxt/http, but the fix might be long in Vercel's module loader.

I'll investigate further and re-open if I see anything actionable on ky's end.
