### ISSUE TITLE
web-streams-polyfill is not really optional

### ISSUE THREAD

**Issue by andrewmclagan** [sindresorhus/ky-universal#24]
The way `web-streams-polyfill` is called makes it a non optional dependancy as it is declared in `package.json`

```js
if (!global.ReadableStream) {
	try {
		global.ReadableStream = require('web-streams-polyfill/ponyfill/es2018');
	} catch (_) {}
}
```

Therefore if the environment simply does not have `ReadableStream`s the dependancy is called. If a developer is not using readable streams they still have to install it. Thus the dependancy is not optional.

**Comment by sindresorhus** [comment]
It's marked as optional:

https://github.com/sindresorhus/ky-universal/blob/d1e9a5d8d325542f40ed2d09104aa6ccfc3cd065/package.json#L68-L72

**Comment by sholladay** [comment]
I don't see the problem here. We mark it as optional because if the dependency is not installed, we catch the load error and don't do anything.

**Comment by andrewmclagan** [comment]
Yarn 2 throws an error. Stating that an optional import is being required. Not sure if thats an issue?

**Comment by sholladay** [comment]
Sounds like they don't detect the `try`. Might be worth asking the Yarn folks whether this is intentional. I would assume not, because if an optional dependency can't be `required()`, then what's the point of having it? They might be using a different definition of "optional" or something, though.
