### ISSUE TITLE
How can I use Ky for react SSR?

### ISSUE THREAD

**Issue by codler** [sindresorhus/ky-universal#27]
How can I use Ky for react SSR?

**Comment by sindresorhus** [comment]
This is in the readme: https://github.com/sindresorhus/ky-universal#how-do-i-use-this-with-a-web-app-react-vuejs-etc-that-uses-server-side-rendering-ssr

**Comment by codler** [comment]
It does not actually show any example of real world usage with React `renderToString`.

**Comment by sholladay** [comment]
What exactly do you want us to show? Should it include the webpack config, server framework with routes, etc? A real SSR setup can get a bit complex depending on your needs.

Generally speaking, I would suggest using something like Next.js that takes care of the rendering under the hood. Then it's really as simple as just calling `ky()` wherever you want to fetch the data.

**Comment by codler** [comment]
Yes please show a real SSR. Otherwise it is very wrong to claim Ky is SSR.

**Comment by sholladay** [comment]
You did not answer my question.
