### ISSUE TITLE
Loading ky-universal from node loads browser.js instead of index.js

### ISSUE THREAD

**Issue by cristobal** [sindresorhus/ky-universal#29]
## Versions information

Node 14
ky@0.26
ky-universal@0.9

## Description
This is a [sample project](https://github.com/cristobal/ky-universal-module-loading-failure) demonstrating the problem. Inside the [package.json](https://github.com/cristobal/ky-universal-module-loading-failure/blob/main/package.json#L10) file we specify that the `.js` files are treated as esm modules.

However running the simple `test.js` sample:

```js
import ky from 'ky-universal'

const parsed = await ky('https://httpbin.org/json').json()
console.log(parsed)
```

Fails i.e:

![Screenshot 2021-01-13 at 13 49 51](https://user-images.githubusercontent.com/155505/104454485-378f4380-55a6-11eb-85c8-843face7a209.png)

The issue seems that it seems to be loading the [`browser.js`](https://github.com/sindresorhus/ky-universal/blob/master/browser.js) variant instead of the [`index.js`](https://github.com/sindresorhus/ky-universal/blob/master/browser.js) which polyfills for the node environment.

E.g. if we explictely import the `index.js` variant that does the polyfill'ing it works as intended:

```js
import ky from './node_modules/ky-universal/index.js'

const parsed = await ky('https://httpbin.org/json').json()
console.log(parsed)
```
![Screenshot 2021-01-13 at 13 53 03](https://user-images.githubusercontent.com/155505/104454790-aa002380-55a6-11eb-9128-3244a92a9013.png)

The problem seem to be related to the changes done in the latest version.
Since the test samples will work perfectly fine with the previous versions of ky and ky-universal.

Checking out the branch `previous-versions` that use `ky@0.25.1` and `ky-universal@0.8.2`
![Screenshot 2021-01-13 at 13 55 54](https://user-images.githubusercontent.com/155505/104455058-0f541480-55a7-11eb-9db2-a93ed0bc7f96.png)

**Comment by cristobal** [comment]
From what i can see changing the `exports.import` field in the `package.json` to the following:

![Screenshot 2021-01-13 at 14 00 43](https://user-images.githubusercontent.com/155505/104455543-bafd6480-55a7-11eb-9fb2-88cef737c294.png)

seems to solve the problem:
![Screenshot 2021-01-13 at 14 01 14](https://user-images.githubusercontent.com/155505/104455590-cea8cb00-55a7-11eb-85bf-54bb311b5e75.png)

**Comment by sindresorhus** [comment]
Thanks for reporting and for the test case. It seems I just slightly misread the docs: https://nodejs.org/api/packages.html#packages_package_entry_points

**Comment by sindresorhus** [comment]
Released a fix: https://github.com/sindresorhus/ky-universal/releases/tag/v0.9.1

**Comment by cristobal** [comment]
Yup i tested the latest version here locally and it works fine 👍
