### ISSUE TITLE
await is only valid in async functions and the top level bodies of modules

### ISSUE THREAD

**Issue by markwoon** [sindresorhus/ky-universal#32]
After updating to 0.9.1 I'm getting:

```
    \node_modules\ky-universal\index.js:58
        globalThis.ReadableStream = await Promise.resolve().then(function () {
                                    ^^^^^

    SyntaxError: await is only valid in async functions and the top level bodies of modules

    > 1 | import ky from 'ky-universal';
        | ^
```

I'm using node v15.6.0.

I'm not quite sure how I'm supposed to fix this.  Any help would be greatly appreciated.

**Comment by sindresorhus** [comment]
Please read the release notes.

**Comment by markwoon** [comment]
I'm sorry, but what am I missing?

* This package is now pure ESM 
  This means you need to use `import ky from 'ky-universal'` instead of `const ky = require('ky-universal')` to import it in Node.js.

I'm doing this.

* Require Node.js 14 

Does ky-universal only work with node 14 and not node 15?

* Now requires Ky 0.26 or later

I am using ky 0.26.0.

**Comment by sholladay** [comment]
It's suspicious that the code your stack trace points to is different than our source code. We don't use `Promise.resolve()`, for example. You must be transpiling `ky-universal`, which I strongly advise against if you can avoid it.

If you're using something like Next.js, ask them if there is a way to modify your config to avoid unnecessary transpiling.

**Comment by sindresorhus** [comment]
https://github.com/vercel/next.js/discussions/21252

**Comment by markwoon** [comment]
I'm using `ky-universal` from jest.

In jest, I have both `ky` and `ky-universal` marked to not be transformed.  But I get:

```
    \node_modules\ky-universal\index.js:58
        globalThis.ReadableStream = await Promise.resolve().then(function () {
                                    ^^^^^

    SyntaxError: await is only valid in async functions and the top level bodies of modules

    > 1 | import ky from 'ky-universal';
        | ^
```

If I also use the `--experimental-vm-modules` node option, I get:

```
    \node_modules\ky-universal\index.js:56
        globalThis.ReadableStream = await import('web-streams-polyfill/ponyfill/es2018');
                                    ^^^^^

    SyntaxError: await is only valid in async functions and the top level bodies of modules

    > 1 | import ky from 'ky-universal';
        | ^
```

**Comment by sholladay** [comment]
@markwoon what version of Node.js are you using? Can you try the latest Node? I would expect Jest or even Webpack to work so long as it's not transpiling Ky. Based on the terminal output you provided, it looks like My is still being transpiled with your configuration. We'll need to figure out how to configure those tools appropriately.

**Comment by markwoon** [comment]
I'm using node v15.6.0.  Do you need me to try the latest LTS release?

I have a pretty vanilla [jest.config.js](https://gist.github.com/markwoon/edfd57ced4ac7cb2ddf32b7309bdd101)

Happy to test anything you can suggest.

**Comment by ShivamJoker** [comment]
Also having the same issue while testing with Jest

**Comment by markwoon** [comment]
@sholladay I've create a very simple test for this @ https://github.com/markwoon/ky-universal-jest

Just run `yarn test` to see the problem.

I would really appreciate to know what it would take to get ky-universal working with jest.

You can ignore/delete the webpack config as that's not needed for jest.  However, you can use the webpack config to test #7.

**Comment by chopfitzroy** [comment]
@markwoon did you get anywhere with this?

**Comment by markwoon** [comment]
@chopfitzroy Sadly, no.  Just decided to switch to something else.

**Comment by sholladay** [comment]
I did run your test repo a while back @markwoon and it was helpful, but at the time I didn't find a working configuration.

However, I just tried it with Jest's updated ESM documentation and it worked perfectly. 

https://jestjs.io/docs/ecmascript-modules

Here is a PR to the test repo: https://github.com/markwoon/ky-universal-jest/pull/1/files
