### ISSUE TITLE
Consider switching to Undici

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ky-universal#34]
It's not stable enough now, but it is likely to become better than `node-fetch`.

https://github.com/Ethan-Arrowood/undici-fetch

**Comment by sholladay** [comment]
Interestingly, `undici` has moved to the Node.js org. Looks like `undici-fetch` probably won't be maintained anymore.

https://github.com/nodejs/undici

**Comment by sindresorhus** [comment]
@sholladay I think they integrated it into the main package: https://github.com/nodejs/undici#undicifetchinput-init-promise

**Comment by liuhanqu** [comment]
Excuse me, can it use `got` to replace `node-fetch` ?

**Comment by sindresorhus** [comment]
@liuhanqu It's possible but difficult as `got` has very a different API. I did explore it in a different package, but never had time to finish it: https://www.npmjs.com/package/kot

**Comment by epaminond** [comment]
It looks like there's some kind of conflict with Undici and it's not working in node 18.x:
https://github.com/mailgun/mailgun.js/issues/275

**Comment by transitive-bullshit** [comment]
I ran into a related issue using Next.js's local dev server, which uses `undici` and https://github.com/vercel/edge-runtime/blob/main/packages/primitives/src/primitives/fetch.js to polyfill `fetch`-related primitives.

It appears that using `ky` in this environment doesn't work as expected. It's possible this is a bug with Next.js's polyfill or `undici` or `ky`. In any case, as it's related, I thought it worth mentioning.

See https://github.com/vercel/next.js/issues/41531 for more details.

**Comment by baraeb92** [comment]
Any updates on this @sindresorhus

**Comment by BlackGlory** [comment]
Undici's performance is [so bad] that there is no need to switch to it now.

[so bad]: https://github.com/nodejs/undici/issues/1203

**Comment by chybisov** [comment]
@sindresorhus do you have any plans on this or is there any example that can be used to map ky and create project-specific ky that uses undici? Thank you 🙂

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ky/releases/tag/v1.0.0
