### ISSUE TITLE
Workaround for ky-universal not being able to be used with Jest

### ISSUE THREAD

**Issue by itsfarseen** [sindresorhus/ky-universal#35]
This is not a bug report or an issue with ky-universal. 
I'm sharing a solution to a problem I had, hoping it would be visible to people having the same problem if I put it here. 
I'd be glad to move it to somewhere else if this is not the best place to share this.

### TLDR;
I wasn't able to import `ky-universal` in a Jest test file. 
I worked around this by creating the following file:
`jest.setup.js`:
```js
const fetch = require('node-fetch');

globalThis.fetch = fetch;
globalThis.Request = fetch.Request;
globalThis.Headers = fetch.Headers;
```

And adding this to `jest.config.js`:
```js
module.exports = {
   ...
   setupFiles: ["./jest.setup.js"],
   ...
}
```

### More details

`ky-universal` is an ES6 module.  
No matter how hard I tried, I was not able to make Jest load an ES6 module. 
It got transformed to something like this, probably by Babel:
```
 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import ky from "ky";
 ```
 And imports can't be anywhere except at the top level in ES6 Modules.
 
 With `ky`, I was able to get it transformed to `cjs` by installing `esbuild`:
 ```yarn add -D esbuild esbuild-jest```
 and adding this in my `jest.config.js`:
 ```js
module.exports = {
    ...
    transform: {
      "^.+\\.(t|j)sx?$": [
        "esbuild-jest",
        {}
      ],
    },
    transformIgnorePatterns: [
      '/node_modules/(?!ky)'
    ]
    ...
}
```

But `ky-universal` is doing top-level await inside it, and neither `esbuild-jest` nor `ts-jest` was able to process top level await.

I tried so hard to make this work with just ES6 support and not using a bundler like esbuild. But I had to conclude this is pretty much impossible after two days of digging.

So I tried to start with just `ky`, which works fine when converted into `cjs` by `esbuild`, and started putting stuff into `globalThis`, one by one, by looking at the errors that came up.

For my code, errors stopped appearing after I assigned the above three things, but there could be more.
If it happens just check the error to see what's missing and add it to `globalThis`.

**Comment by yungo1846** [comment]
Thank you @itsfarseen 👍 
After adopting your solution, it worked well!

Note:
In my project, node-fetch v3 didn't work. Only v2 worked
