### ISSUE TITLE
Using Ky breaks Vuex

### ISSUE THREAD

**Issue by RobsonMi** [sindresorhus/ky-universal#38]
I am writing an app for web and electron using Quasar. I wanted to move from axios to Ky but as soon as I replace it Vuex store refuses to accept changes to it's state. store.commit works and I am able to log payload data and current store values but no mutations are accepted by store without any errors or warnings. This is very interesting and I can't pin where it fails. Any help would be appreciated.

**Comment by darrinmn9** [comment]
I have a large app with Vue/Vuex + Ky and it works just fine. It is most likely something specific to your app. 

Also, how can you expect someone to help you without any repro steps, error messages, code, dependency versions, etc?

**Comment by sholladay** [comment]
Closing for lack of info. As Darrin said, at the very least we would need some reproduction steps or other specific details to move forward in helping you.

That said, my best guess given your description is that you reinstalled your dependencies while migrating to Ky. In doing so, you probably also (perhaps unknowingly) updated Vuex or other dependencies. This can happen even if you have pinned dependency versions in your package.json, if you ever run `npm install` by itself (without a specific package name).
