### ISSUE TITLE
Can't access `HTTPError` etc. from `ky-universal`

### ISSUE THREAD

**Issue by RafalFilipek** [sindresorhus/ky-universal#39]
Hi, 

For some reason, I can't access `HTTPError` from this package. Import from `ky` package works just fine. 

```
import { HTTPError } from "ky-universal";
import { HTTPError as HTTPErrorFromKy } from "ky";

/**
 * prints {HTTPError: undefined, HTTPErrorFromKy: ƒ HTTPError()}
 */
console.log({ HTTPError, HTTPErrorFromKy });
```

https://codesandbox.io/s/red-field-qdh1d7?file=/src/index.js

Thank you,

Rafał

**Comment by sholladay** [comment]
We don't currently re-export Ky's named exports. I don't have a strong opinion on whether or not we should re-export, but the docs should be updated to clarify this either way.

**Comment by sindresorhus** [comment]
It's just an oversight. It should definitely be re-exported. We already re-export it in the types.
