### ISSUE TITLE
Error classes are not exposed

### ISSUE THREAD

**Issue by arty-name** [sindresorhus/ky-universal#4]
The error classes `HTTPError` and `TimeoutError` seem to be inaccessible through `ky-universal`. It only re-exports the default export of `ky/umd`, not these classes. Following workaround can only be found by inspecting the source code: 

```javascript
const { HTTPError, TimeoutError } = require('ky/umd')
```

I think it is reasonable to expect following to work: 

```javascript
const { HTTPError, TimeoutError } = require('ky-universal')
```

Would you accept a PR implementing this?

**Comment by sindresorhus** [comment]
Just an oversight. PR welcome.

**Comment by arty-name** [comment]
Here you go!

**Comment by arty-name** [comment]
Thanks!
