### ISSUE TITLE
HighWatermark FAQ clarification

### ISSUE THREAD

**Issue by pd8** [sindresorhus/ky-universal#43]
Hi hopefully this is an easy / quick answer

In the FAQ here: https://github.com/sindresorhus/ky-universal#clone-hangs-with-a-large-response-in-node---what-should-i-do
It's stated that Ky is used under the hood and has a default highWatermark of 10mb.

However when using ky-universal I run into issues with cloning at 20kb and looking through https://github.com/sindresorhus/ky I (perhaps naively) don't think a highWatermark default is being set.

Perhaps I'm just missing it, but would be great to get clarification on this.

Thanks in advance.

**Comment by sindresorhus** [comment]
It's set in the `fetch` polyfill, not in Ky: https://github.com/sindresorhus/ky-universal/blob/bf97ae52d4ab0b91182b98b110dfb2ff54c59972/index.js#L8

**Comment by pd8** [comment]
Thanks for answering, that's strange, it's not working for me at 20kb using ky-universal. I'll try to create a minimum example and show it.

**Comment by pd8** [comment]
Ah apologies, the internal package we were using was using an old ky-universal package (0.2.2), before the highwatermark was introduced, my mistake!
