### ISSUE TITLE
Create-React-App testing fails with ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by danielbakas** [sindresorhus/ky-universal#45]
Hi there,

Running a simple test fails saying that Buffer is not defined. I tried `npm i buffer --save` but that didn't work.

Here's the test:
```js
describe("App", () => {
    it("render", () => {
        render(App);
    });
});
```

And here's the log:
```console
  ● Test suite failed to run

    /Users/danielbakas/Documents/Profesional/Semantyk/Projects/Semantyk/client/node_modules/ky-universal/node_modules/node-fetch/src/utils/form-data.js:1
    ReferenceError: Buffer is not defined

      at Object.<anonymous> (node_modules/ky-universal/node_modules/node-fetch/src/utils/form-data.js:7:24)
```

Any idea on how to fix this?

Thanks 😋

**Comment by sindresorhus** [comment]
This would be better asked in the CRA issue tracker. It sounds like it picks the incorrect export: https://github.com/sindresorhus/ky-universal/blob/349bbe429dd9a9bed7d1cf18d1a2c4ff4b656fe0/package.json#L14-L17

**Comment by danielbakas** [comment]
Thanks!
