### ISSUE TITLE
Reference Error : Buffer is not defined.

### ISSUE THREAD

**Issue by argahsuknesib** [sindresorhus/ky-universal#48]
Hello, I am using a package which uses ky-universal as a dependency.
I am getting an error while executing on the ky-universal package that 
```

    /home/kush/Code/solid-stream-aggregator/node_modules/ky-universal/node_modules/node-fetch/src/utils/form-data.js:1
    ReferenceError: Buffer is not defined

      at Object.<anonymous> (node_modules/ky-universal/node_modules/node-fetch/src/utils/form-data.js:7:24)
```

**Comment by sindresorhus** [comment]
The error is coming from `node-fetch`, not this package. My guess would be that your bundler config is incorrect.
