### ISSUE TITLE
Polyfill ReadableStream

### ISSUE THREAD

**Issue by jdalrymple** [sindresorhus/ky-universal#6]
Would it make sense to polyfill readable stream in the node stream library or https://www.npmjs.com/package/web-streams-polyfill? Otherwise the onDownloadProgress option isn't usable for non-browsers

**Comment by sholladay** [comment]
Hmm is there some way we can adapt the Node.js streams implementation to be compatible? That would be nice.

Also worth mentioning, it's my under standing that Node will be adopting WHATWG streams soon. And Deno already has it. Most environments do, Node is a straggler here.

**Comment by jdalrymple** [comment]
I was looking to see if that could be done with the Node.js stream implementation, but would have to look further to come up with something

**Comment by jdalrymple** [comment]
Better yet would just be exposing the fetch streaming capabilities

**Comment by sindresorhus** [comment]
I'm not sure. Would be nice if it just worked, but that also means that everyone has to pay for something the majority would not use. The package is also quite big on disk: https://packagephobia.now.sh/result?p=web-streams-polyfill

**Comment by Richienb** [comment]
We could include it as an optional dependency which users could install if they need the functionality.

**Comment by sindresorhus** [comment]
@Richienb I assume you mean optional **peer** dependency. Yes, that could work.
