### ISSUE TITLE
fetch and electron renderer fail

### ISSUE THREAD

**Issue by hugomrdias** [sindresorhus/ky-universal#9]
In a electron renderer thread if you don't bundle (nodeIntegration===true) you get whatever main prop a package points to, in this case we get the node version of ky. 

But if we look at these lines https://github.com/sindresorhus/ky-universal/blob/master/index.js#L14-L16 we will get into troubles because the if clause tests if `global.fetch` exists and in electron renderer that will be true because native web fetch is available. 

So instead of using node-fetch we use native fetch, but when another package using `ky` uses https://github.com/form-data/form-data with fetch it fails because `form-data` only works with node-fetch.

To fix this either we detect the environment for this specific case and workaround it or we remove the if clauses since `ky` already allows for lazy resolution of globals.

I'm happy to PR a fix, but would like some feedback on this first.

**Comment by sholladay** [comment]
> form-data only works with node-fetch

This sounds like the root of the problem. Why does the `form-data` library not work with native `fetch`? What exactly does it do when you pass one of its `FormData` instances to native `fetch`?

I would assume that native `FormData` is available in an Electron renderer process, so why is a polyfill library even being used? In my opinion, the bootstrapping code that is causing the native vs non-native mismatch is probably being a bit too naive. If so, then I'm not 100% convinced that a workaround necessarily belongs in `ky-universal`, given that we are not importing `form-data` ourselves. It seems like whoever is doing that has the responsibility of ensuring it is compatible with the current environment.

If you still want to do a workaround, it would still be easy to assign `node-fetch` to `global.fetch` within your app. But again, that seems bad to me.

**Comment by hugomrdias** [comment]
form-data uses node-streams

As to why we are using form-data and web fetch:
our code base is mostly isomorphic by using swaps for browser using the `browser` property in package.json but that only works when bundling.

In this case (electron-renderer) a user can either bundle or not, if the user bundles everything works as expected, but if it doesn't stuff breaks. 

So why it breaks, without bundling electron-renderer works just like node, it follows the main property in package.json basically using the node version of the code and that is fine because of the node integration electron has.

The problem happens when it tries to run the ky-universal node version which checks for `global.fetch` and that in electron-renderer is true because its chromium, and we get node form-data and web fetch.

A question, what is the reasoning behind checking if global.fetch exists?

**Comment by sindresorhus** [comment]
> A question, what is the reasoning behind checking if global.fetch exists?

We don't want to override the native `fetch` if it exists. That would mean other things expecting the native `fetch` would fail if they used some feature the polyfill couldn't support.

**Comment by Richienb** [comment]
This problem should be fixed by https://github.com/node-fetch/node-fetch/pull/603 in node-fetch v3 since it [duck tests](https://github.com/node-fetch/node-fetch/pull/603/files#diff-11224b4fae1363571897b51a9cc735adR53-R67) for FormData.

**Comment by brandonpittman** [comment]
I’m seeing an issue where global.fetch isn’t a function as well. Obviously works fine in dev. Fails on SSG build.

**Comment by Richienb** [comment]
In the browser context, you can just import ky with `require("ky/umd")`.
